### ISSUE TITLE
De computer is gehacked! Deze moet dus weg.

### ISSUE THREAD

**Issue by DusDavidGames** [DeveloperBoy/MinetopiaPC#2]
Ik heb gezien, dat deze computer is gehacked! Deze moet dus nu weg.

**Comment by DusDavidGames** [comment]
Heb wel pas net github aangemaakt op verzoek van een van mijn devs. Ben jij uberhaupt een dev? ;)

**Comment by DeveloperBoy** [comment]
Natuurlijk ben ik een dev. Het lijkt me niet dat jij opeens een account aanmaakt...

**Comment by DusDavidGames** [comment]
Nogmaals op verzoek van een van mijn devs, maar nu verzoek ik je namens heel de DDG server, deze repo te verwijderen.

**Comment by DeveloperBoy** [comment]
Heb je bewijs dat je de echte bent. Nee dus...

**Comment by DusDavidGames** [comment]
And, for the record, een van onze devs zei dat jouw code heel skeer is. 👍

**Comment by DusDavidGames** [comment]
Tuurlijk wel, zeg maar wat je wil zien! :)

**Comment by DeveloperBoy** [comment]
Wat heb je. Stuur maar...

**Comment by DusDavidGames** [comment]
Zou niet weten hoe ik verder kan bewijzen dat ik ik ben.. Nogmaals, zeg maar wat je wil zien! :)
